apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-store-csi-driver-binding
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: vault
roleRef:
  kind: ClusterRole
  name: secrets-store-csi-driver-role
  apiGroup: rbac.authorization.k8s.io
